services:
  reliab_test:
    build:
      context: .
      dockerfile: .docker/dev.Dockerfile
    env_file:
      - .env
    volumes:
      - ./:/app/reliab-test:delegated
      - ./.docker/entrypoints/dev.sh:/entrypoint.sh:ro
    entrypoint: /entrypoint.sh
    ports:
      - 8080:8080
    depends_on:
      - pg
    networks:
      - reliab

  pg:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_USER: reliab_user
      POSTGRES_PASSWORD: reliab_password
      POSTGRES_DB: reliab
      SERVICE_NAME: pg
      POSTGRES_HOST_AUTH_METHOD: trust
    expose:
      - "5432"
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - data:/var/lib/postgresql
    networks:
      - reliab

volumes:
  data:

networks:
  reliab: